project-includes = [
    "python/**/*.py",
]

project-excludes = [
    "**/node_modules/**",
    "**/.venv/**",
    "**/clip-app/**",
]

search-path = [
    "python",
    ".",
]

site-package-path = [
    ".venv/Lib/site-packages",
]

python-interpreter-path = ".venv/Scripts/python.exe"

replace-imports-with-any = [
    "faster_whisper",
    "whisper",
    "cv2",
    "numpy",
]

enabled-ignores = ["type", "pyrefly", "pyright", "mypy", "ty", "pyre", "zuban"]
check-unannotated-defs = false
