// Kept in sync with the static caption editor catalog.
const CATEGORIES = ["Clean", "Bold", "Editorial", "Accent", "Labels", "Cinema"];

const CAPTION_PRESETS = [
  {
    "id": "studio-studio-clean",
    "name": "Studio Clean",
    "category": "Clean",
    "previewText": "Make it happen",
    "behindPerson": false,
    "style": {
      "curated": true,
      "fontFamily": "Barlow",
      "fontWeight": 700,
      "fontSize": 28,
      "textTransform": "none",
      "textColor": "#FFFFFF",
      "highlightColor": "#FFFFFF",
      "highlightMode": "none",
      "strokeColor": "#111318",
      "strokeWidth": 1,
      "bgColor": "#111318",
      "bgOpacity": 0,
      "bgPadding": 6,
      "borderRadius": 6,
      "textShadow": true,
      "shadowColor": "#000000",
      "shadowBlur": 3,
      "shadowOffsetX": 0,
      "shadowOffsetY": 2,
      "glowIntensity": 0,
      "filter": "none",
      "backdropFilter": "none",
      "wordAnimation": "classic",
      "presetDuration": 0.2,
      "wordsInRow": "3 Words",
      "letterSpacing": 0,
      "lineSpacing": 1.15
    },
    "quickPick": true
  },
  {
    "id": "studio-soft-focus",
    "name": "Soft Focus",
    "category": "Clean",
    "previewText": "Small moments",
    "behindPerson": false,
    "style": {
      "curated": true,
      "fontFamily": "Barlow",
      "fontWeight": 700,
      "fontSize": 25,
      "textTransform": "none",
      "textColor": "#FFFFFF",
      "highlightColor": "#FFFFFF",
      "highlightMode": "none",
      "strokeColor": "#111318",
      "strokeWidth": 0,
      "bgColor": "#111318",
      "bgOpacity": 0,
      "bgPadding": 6,
      "borderRadius": 6,
      "textShadow": true,
      "shadowColor": "#000000",
      "shadowBlur": 5,
      "shadowOffsetX": 0,
      "shadowOffsetY": 2,
      "glowIntensity": 0,
      "filter": "none",
      "backdropFilter": "none",
      "wordAnimation": "elevate",
      "presetDuration": 0.2,
      "wordsInRow": "3 Words",
      "letterSpacing": 0,
      "lineSpacing": 1.15
    }
  },
  {
    "id": "studio-compact",
    "name": "Compact",
    "category": "Clean",
    "previewText": "KEEP MOVING",
    "behindPerson": false,
    "style": {
      "curated": true,
      "fontFamily": "Barlow Condensed",
      "fontWeight": 700,
      "fontSize": 32,
      "textTransform": "uppercase",
      "textColor": "#FFFFFF",
      "highlightColor": "#FFFFFF",
      "highlightMode": "none",
      "strokeColor": "#111318",
      "strokeWidth": 1,
      "bgColor": "#111318",
      "bgOpacity": 0,
      "bgPadding": 6,
      "borderRadius": 6,
      "textShadow": true,
      "shadowColor": "#000000",
      "shadowBlur": 3,
      "shadowOffsetX": 0,
      "shadowOffsetY": 2,
      "glowIntensity": 0,
      "filter": "none",
      "backdropFilter": "none",
      "wordAnimation": "classic",
      "presetDuration": 0.2,
      "wordsInRow": "2 Words",
      "letterSpacing": 0,
      "lineSpacing": 1.15
    }
  },
  {
    "id": "studio-quiet-mono",
    "name": "Quiet Mono",
    "category": "Clean",
    "previewText": "one step ahead",
    "behindPerson": false,
    "style": {
      "curated": true,
      "fontFamily": "Space Mono",
      "fontWeight": 400,
      "fontSize": 22,
      "textTransform": "none",
      "textColor": "#FFFFFF",
      "highlightColor": "#FFFFFF",
      "highlightMode": "none",
      "strokeColor": "#111318",
      "strokeWidth": 0,
      "bgColor": "#111318",
      "bgOpacity": 0,
      "bgPadding": 6,
      "borderRadius": 6,
      "textShadow": true,
      "shadowColor": "#000000",
      "shadowBlur": 3,
      "shadowOffsetX": 0,
      "shadowOffsetY": 2,
      "glowIntensity": 0,
      "filter": "none",
      "backdropFilter": "none",
      "wordAnimation": "none",
      "presetDuration": 0.2,
      "wordsInRow": "3 Words",
      "letterSpacing": 0,
      "lineSpacing": 1.15
    }
  },
  {
    "id": "studio-headline",
    "name": "Headline",
    "category": "Bold",
    "previewText": "MAKE IT COUNT",
    "behindPerson": false,
    "style": {
      "curated": true,
      "fontFamily": "Anton",
      "fontWeight": 400,
      "fontSize": 32,
      "textTransform": "uppercase",
      "textColor": "#FFFFFF",
      "highlightColor": "#FFFFFF",
      "highlightMode": "none",
      "strokeColor": "#111318",
      "strokeWidth": 2,
      "bgColor": "#111318",
      "bgOpacity": 0,
      "bgPadding": 6,
      "borderRadius": 6,
      "textShadow": true,
      "shadowColor": "#000000",
      "shadowBlur": 3,
      "shadowOffsetX": 0,
      "shadowOffsetY": 2,
      "glowIntensity": 0,
      "filter": "none",
      "backdropFilter": "none",
      "wordAnimation": "pop",
      "presetDuration": 0.2,
      "wordsInRow": "2 Words",
      "letterSpacing": 0,
      "lineSpacing": 1.15
    },
    "quickPick": true
  },
  {
    "id": "studio-tall-type",
    "name": "Tall Type",
    "category": "Bold",
    "previewText": "STAY CURIOUS",
    "behindPerson": false,
    "style": {
      "curated": true,
      "fontFamily": "Bebas Neue",
      "fontWeight": 400,
      "fontSize": 38,
      "textTransform": "uppercase",
      "textColor": "#FFFFFF",
      "highlightColor": "#FFFFFF",
      "highlightMode": "none",
      "strokeColor": "#111318",
      "strokeWidth": 1,
      "bgColor": "#111318",
      "bgOpacity": 0,
      "bgPadding": 6,
      "borderRadius": 6,
      "textShadow": true,
      "shadowColor": "#000000",
      "shadowBlur": 3,
      "shadowOffsetX": 0,
      "shadowOffsetY": 2,
      "glowIntensity": 0,
      "filter": "none",
      "backdropFilter": "none",
      "wordAnimation": "elevate",
      "presetDuration": 0.2,
      "wordsInRow": "2 Words",
      "letterSpacing": 1,
      "lineSpacing": 1.15
    }
  },
  {
    "id": "studio-impact-white",
    "name": "Impact White",
    "category": "Bold",
    "previewText": "ONE THING",
    "behindPerson": false,
    "style": {
      "curated": true,
      "fontFamily": "Barlow Condensed",
      "fontWeight": 700,
      "fontSize": 36,
      "textTransform": "uppercase",
      "textColor": "#FFFFFF",
      "highlightColor": "#FFFFFF",
      "highlightMode": "none",
      "strokeColor": "#111318",
      "strokeWidth": 2,
      "bgColor": "#111318",
      "bgOpacity": 0,
      "bgPadding": 6,
      "borderRadius": 6,
      "textShadow": true,
      "shadowColor": "#000000",
      "shadowBlur": 3,
      "shadowOffsetX": 0,
      "shadowOffsetY": 2,
      "glowIntensity": 0,
      "filter": "none",
      "backdropFilter": "none",
      "wordAnimation": "pop",
      "presetDuration": 0.2,
      "wordsInRow": "2 Words",
      "letterSpacing": 0,
      "lineSpacing": 1.15
    }
  },
  {
    "id": "studio-solo",
    "name": "Solo",
    "category": "Bold",
    "previewText": "FOCUS",
    "behindPerson": false,
    "style": {
      "curated": true,
      "fontFamily": "Anton",
      "fontWeight": 400,
      "fontSize": 38,
      "textTransform": "uppercase",
      "textColor": "#FFFFFF",
      "highlightColor": "#FFFFFF",
      "highlightMode": "none",
      "strokeColor": "#111318",
      "strokeWidth": 1,
      "bgColor": "#111318",
      "bgOpacity": 0,
      "bgPadding": 6,
      "borderRadius": 6,
      "textShadow": true,
      "shadowColor": "#000000",
      "shadowBlur": 3,
      "shadowOffsetX": 0,
      "shadowOffsetY": 2,
      "glowIntensity": 0,
      "filter": "none",
      "backdropFilter": "none",
      "wordAnimation": "pop",
      "presetDuration": 0.2,
      "wordsInRow": "1 Word",
      "letterSpacing": 0,
      "lineSpacing": 1.15
    }
  },
  {
    "id": "studio-storybook",
    "name": "Storybook",
    "category": "Editorial",
    "previewText": "A different view",
    "behindPerson": false,
    "style": {
      "curated": true,
      "fontFamily": "Libre Caslon Text",
      "fontWeight": 400,
      "fontSize": 25,
      "textTransform": "none",
      "textColor": "#FFFFFF",
      "highlightColor": "#FFFFFF",
      "highlightMode": "none",
      "strokeColor": "#111318",
      "strokeWidth": 0,
      "bgColor": "#111318",
      "bgOpacity": 0,
      "bgPadding": 6,
      "borderRadius": 6,
      "textShadow": true,
      "shadowColor": "#000000",
      "shadowBlur": 4,
      "shadowOffsetX": 0,
      "shadowOffsetY": 2,
      "glowIntensity": 0,
      "filter": "none",
      "backdropFilter": "none",
      "wordAnimation": "classic",
      "presetDuration": 0.2,
      "wordsInRow": "3 Words",
      "letterSpacing": 0,
      "lineSpacing": 1.15
    },
    "quickPick": true
  },
  {
    "id": "studio-the-interview",
    "name": "The Interview",
    "category": "Editorial",
    "previewText": "Tell your story",
    "behindPerson": false,
    "style": {
      "curated": true,
      "fontFamily": "Libre Caslon Text",
      "fontWeight": 400,
      "fontSize": 26,
      "textTransform": "none",
      "textColor": "#FFFFFF",
      "highlightColor": "#FFFFFF",
      "highlightMode": "none",
      "strokeColor": "#111318",
      "strokeWidth": 0,
      "bgColor": "#111318",
      "bgOpacity": 85,
      "bgPadding": 8,
      "borderRadius": 2,
      "textShadow": true,
      "shadowColor": "#000000",
      "shadowBlur": 3,
      "shadowOffsetX": 0,
      "shadowOffsetY": 2,
      "glowIntensity": 0,
      "filter": "none",
      "backdropFilter": "none",
      "wordAnimation": "none",
      "presetDuration": 0.2,
      "wordsInRow": "3 Words",
      "letterSpacing": 0,
      "lineSpacing": 1.15
    }
  },
  {
    "id": "studio-warm-paper",
    "name": "Warm Paper",
    "category": "Editorial",
    "previewText": "Take your time",
    "behindPerson": false,
    "style": {
      "curated": true,
      "fontFamily": "Libre Caslon Text",
      "fontWeight": 400,
      "fontSize": 24,
      "textTransform": "none",
      "textColor": "#F4E7CE",
      "highlightColor": "#FFFFFF",
      "highlightMode": "none",
      "strokeColor": "#111318",
      "strokeWidth": 0,
      "bgColor": "#111318",
      "bgOpacity": 0,
      "bgPadding": 6,
      "borderRadius": 6,
      "textShadow": true,
      "shadowColor": "#000000",
      "shadowBlur": 3,
      "shadowOffsetX": 0,
      "shadowOffsetY": 2,
      "glowIntensity": 0,
      "filter": "none",
      "backdropFilter": "none",
      "wordAnimation": "elevate",
      "presetDuration": 0.2,
      "wordsInRow": "3 Words",
      "letterSpacing": 0,
      "lineSpacing": 1.15
    }
  },
  {
    "id": "studio-field-notes",
    "name": "Field Notes",
    "category": "Editorial",
    "previewText": "a little closer",
    "behindPerson": false,
    "style": {
      "curated": true,
      "fontFamily": "Space Mono",
      "fontWeight": 400,
      "fontSize": 21,
      "textTransform": "none",
      "textColor": "#20241E",
      "highlightColor": "#FFFFFF",
      "highlightMode": "none",
      "strokeColor": "#111318",
      "strokeWidth": 0,
      "bgColor": "#EEE8DC",
      "bgOpacity": 100,
      "bgPadding": 8,
      "borderRadius": 2,
      "textShadow": false,
      "shadowColor": "#000000",
      "shadowBlur": 0,
      "shadowOffsetX": 0,
      "shadowOffsetY": 2,
      "glowIntensity": 0,
      "filter": "none",
      "backdropFilter": "none",
      "wordAnimation": "none",
      "presetDuration": 0.2,
      "wordsInRow": "3 Words",
      "letterSpacing": 0,
      "lineSpacing": 1.15
    }
  },
  {
    "id": "studio-lime-cue",
    "name": "Lime Cue",
    "category": "Accent",
    "previewText": "Find your voice",
    "behindPerson": false,
    "style": {
      "curated": true,
      "fontFamily": "Barlow",
      "fontWeight": 700,
      "fontSize": 28,
      "textTransform": "none",
      "textColor": "#FFFFFF",
      "highlightColor": "#C5F568",
      "highlightMode": "word",
      "strokeColor": "#111318",
      "strokeWidth": 1,
      "bgColor": "#111318",
      "bgOpacity": 0,
      "bgPadding": 6,
      "borderRadius": 6,
      "textShadow": true,
      "shadowColor": "#000000",
      "shadowBlur": 3,
      "shadowOffsetX": 0,
      "shadowOffsetY": 2,
      "glowIntensity": 0,
      "filter": "none",
      "backdropFilter": "none",
      "wordAnimation": "pop",
      "presetDuration": 0.2,
      "wordsInRow": "3 Words",
      "letterSpacing": 0,
      "lineSpacing": 1.15
    },
    "quickPick": true
  },
  {
    "id": "studio-golden-hour",
    "name": "Golden Hour",
    "category": "Accent",
    "previewText": "Good things ahead",
    "behindPerson": false,
    "style": {
      "curated": true,
      "fontFamily": "Barlow",
      "fontWeight": 700,
      "fontSize": 29,
      "textTransform": "none",
      "textColor": "#FFFFFF",
      "highlightColor": "#FFD761",
      "highlightMode": "word",
      "strokeColor": "#111318",
      "strokeWidth": 1,
      "bgColor": "#111318",
      "bgOpacity": 0,
      "bgPadding": 6,
      "borderRadius": 6,
      "textShadow": true,
      "shadowColor": "#000000",
      "shadowBlur": 3,
      "shadowOffsetX": 0,
      "shadowOffsetY": 2,
      "glowIntensity": 0,
      "filter": "none",
      "backdropFilter": "none",
      "wordAnimation": "elevate",
      "presetDuration": 0.2,
      "wordsInRow": "3 Words",
      "letterSpacing": 0,
      "lineSpacing": 1.15
    }
  },
  {
    "id": "studio-ice-blue",
    "name": "Ice Blue",
    "category": "Accent",
    "previewText": "Keep it simple",
    "behindPerson": false,
    "style": {
      "curated": true,
      "fontFamily": "Barlow Condensed",
      "fontWeight": 700,
      "fontSize": 32,
      "textTransform": "none",
      "textColor": "#FFFFFF",
      "highlightColor": "#83DEFF",
      "highlightMode": "word",
      "strokeColor": "#111318",
      "strokeWidth": 1,
      "bgColor": "#111318",
      "bgOpacity": 0,
      "bgPadding": 6,
      "borderRadius": 6,
      "textShadow": true,
      "shadowColor": "#000000",
      "shadowBlur": 3,
      "shadowOffsetX": 0,
      "shadowOffsetY": 2,
      "glowIntensity": 0,
      "filter": "none",
      "backdropFilter": "none",
      "wordAnimation": "classic",
      "presetDuration": 0.2,
      "wordsInRow": "3 Words",
      "letterSpacing": 0,
      "lineSpacing": 1.15
    }
  },
  {
    "id": "studio-rose-cue",
    "name": "Rose Cue",
    "category": "Accent",
    "previewText": "Trust the process",
    "behindPerson": false,
    "style": {
      "curated": true,
      "fontFamily": "Barlow",
      "fontWeight": 700,
      "fontSize": 27,
      "textTransform": "none",
      "textColor": "#FFFFFF",
      "highlightColor": "#FFB8CE",
      "highlightMode": "word",
      "strokeColor": "#111318",
      "strokeWidth": 1,
      "bgColor": "#111318",
      "bgOpacity": 0,
      "bgPadding": 6,
      "borderRadius": 6,
      "textShadow": true,
      "shadowColor": "#000000",
      "shadowBlur": 3,
      "shadowOffsetX": 0,
      "shadowOffsetY": 2,
      "glowIntensity": 0,
      "filter": "none",
      "backdropFilter": "none",
      "wordAnimation": "classic",
      "presetDuration": 0.2,
      "wordsInRow": "3 Words",
      "letterSpacing": 0,
      "lineSpacing": 1.15
    }
  },
  {
    "id": "studio-dark-label",
    "name": "Dark Label",
    "category": "Labels",
    "previewText": "Say it clearly",
    "behindPerson": false,
    "style": {
      "curated": true,
      "fontFamily": "Barlow",
      "fontWeight": 700,
      "fontSize": 28,
      "textTransform": "none",
      "textColor": "#FFFFFF",
      "highlightColor": "#FFFFFF",
      "highlightMode": "none",
      "strokeColor": "#111318",
      "strokeWidth": 0,
      "bgColor": "#111318",
      "bgOpacity": 90,
      "bgPadding": 8,
      "borderRadius": 6,
      "textShadow": false,
      "shadowColor": "#000000",
      "shadowBlur": 0,
      "shadowOffsetX": 0,
      "shadowOffsetY": 2,
      "glowIntensity": 0,
      "filter": "none",
      "backdropFilter": "none",
      "wordAnimation": "classic",
      "presetDuration": 0.2,
      "wordsInRow": "3 Words",
      "letterSpacing": 0,
      "lineSpacing": 1.15
    },
    "quickPick": true
  },
  {
    "id": "studio-white-label",
    "name": "White Label",
    "category": "Labels",
    "previewText": "Fresh perspective",
    "behindPerson": false,
    "style": {
      "curated": true,
      "fontFamily": "Barlow",
      "fontWeight": 700,
      "fontSize": 28,
      "textTransform": "none",
      "textColor": "#15171B",
      "highlightColor": "#FFFFFF",
      "highlightMode": "none",
      "strokeColor": "#111318",
      "strokeWidth": 0,
      "bgColor": "#FAF8F2",
      "bgOpacity": 100,
      "bgPadding": 8,
      "borderRadius": 6,
      "textShadow": false,
      "shadowColor": "#000000",
      "shadowBlur": 0,
      "shadowOffsetX": 0,
      "shadowOffsetY": 2,
      "glowIntensity": 0,
      "filter": "none",
      "backdropFilter": "none",
      "wordAnimation": "elevate",
      "presetDuration": 0.2,
      "wordsInRow": "3 Words",
      "letterSpacing": 0,
      "lineSpacing": 1.15
    }
  },
  {
    "id": "studio-sunflower",
    "name": "Sunflower",
    "category": "Labels",
    "previewText": "GOOD ENERGY",
    "behindPerson": false,
    "style": {
      "curated": true,
      "fontFamily": "Barlow Condensed",
      "fontWeight": 700,
      "fontSize": 30,
      "textTransform": "uppercase",
      "textColor": "#171811",
      "highlightColor": "#FFFFFF",
      "highlightMode": "none",
      "strokeColor": "#111318",
      "strokeWidth": 0,
      "bgColor": "#F5CE48",
      "bgOpacity": 100,
      "bgPadding": 8,
      "borderRadius": 3,
      "textShadow": false,
      "shadowColor": "#000000",
      "shadowBlur": 0,
      "shadowOffsetX": 0,
      "shadowOffsetY": 2,
      "glowIntensity": 0,
      "filter": "none",
      "backdropFilter": "none",
      "wordAnimation": "pop",
      "presetDuration": 0.2,
      "wordsInRow": "3 Words",
      "letterSpacing": 0,
      "lineSpacing": 1.15
    }
  },
  {
    "id": "studio-midnight",
    "name": "Midnight",
    "category": "Labels",
    "previewText": "A new beginning",
    "behindPerson": false,
    "style": {
      "curated": true,
      "fontFamily": "Barlow",
      "fontWeight": 700,
      "fontSize": 26,
      "textTransform": "none",
      "textColor": "#EAF2FF",
      "highlightColor": "#FFFFFF",
      "highlightMode": "none",
      "strokeColor": "#111318",
      "strokeWidth": 0,
      "bgColor": "#172B46",
      "bgOpacity": 95,
      "bgPadding": 8,
      "borderRadius": 6,
      "textShadow": false,
      "shadowColor": "#000000",
      "shadowBlur": 0,
      "shadowOffsetX": 0,
      "shadowOffsetY": 2,
      "glowIntensity": 0,
      "filter": "none",
      "backdropFilter": "none",
      "wordAnimation": "classic",
      "presetDuration": 0.2,
      "wordsInRow": "3 Words",
      "letterSpacing": 0,
      "lineSpacing": 1.15
    }
  },
  {
    "id": "studio-documentary",
    "name": "Documentary",
    "category": "Cinema",
    "previewText": "Beyond the ordinary",
    "behindPerson": false,
    "style": {
      "curated": true,
      "fontFamily": "Barlow",
      "fontWeight": 700,
      "fontSize": 24,
      "textTransform": "none",
      "textColor": "#FFFFFF",
      "highlightColor": "#FFFFFF",
      "highlightMode": "none",
      "strokeColor": "#111318",
      "strokeWidth": 0,
      "bgColor": "#111318",
      "bgOpacity": 0,
      "bgPadding": 6,
      "borderRadius": 6,
      "textShadow": true,
      "shadowColor": "#000000",
      "shadowBlur": 5,
      "shadowOffsetX": 0,
      "shadowOffsetY": 2,
      "glowIntensity": 0,
      "filter": "none",
      "backdropFilter": "none",
      "wordAnimation": "none",
      "presetDuration": 0.2,
      "wordsInRow": "4 Words",
      "letterSpacing": 0,
      "lineSpacing": 1.15
    }
  },
  {
    "id": "studio-wide-screen",
    "name": "Wide Screen",
    "category": "Cinema",
    "previewText": "THE NEXT CHAPTER",
    "behindPerson": false,
    "style": {
      "curated": true,
      "fontFamily": "Bebas Neue",
      "fontWeight": 400,
      "fontSize": 32,
      "textTransform": "uppercase",
      "textColor": "#FFFFFF",
      "highlightColor": "#FFFFFF",
      "highlightMode": "none",
      "strokeColor": "#111318",
      "strokeWidth": 0,
      "bgColor": "#111318",
      "bgOpacity": 0,
      "bgPadding": 6,
      "borderRadius": 6,
      "textShadow": true,
      "shadowColor": "#000000",
      "shadowBlur": 3,
      "shadowOffsetX": 0,
      "shadowOffsetY": 2,
      "glowIntensity": 0,
      "filter": "none",
      "backdropFilter": "none",
      "wordAnimation": "elevate",
      "presetDuration": 0.2,
      "wordsInRow": "3 Words",
      "letterSpacing": 2,
      "lineSpacing": 1.15
    },
    "quickPick": true
  },
  {
    "id": "studio-film-title",
    "name": "Film Title",
    "category": "Cinema",
    "previewText": "The art of living",
    "behindPerson": false,
    "style": {
      "curated": true,
      "fontFamily": "Libre Caslon Text",
      "fontWeight": 400,
      "fontSize": 27,
      "textTransform": "none",
      "textColor": "#FFFFFF",
      "highlightColor": "#FFFFFF",
      "highlightMode": "none",
      "strokeColor": "#111318",
      "strokeWidth": 0,
      "bgColor": "#111318",
      "bgOpacity": 0,
      "bgPadding": 6,
      "borderRadius": 6,
      "textShadow": true,
      "shadowColor": "#000000",
      "shadowBlur": 3,
      "shadowOffsetX": 0,
      "shadowOffsetY": 2,
      "glowIntensity": 0,
      "filter": "none",
      "backdropFilter": "none",
      "wordAnimation": "classic",
      "presetDuration": 0.2,
      "wordsInRow": "3 Words",
      "letterSpacing": 0.5,
      "lineSpacing": 1.15
    }
  },
  {
    "id": "studio-amber-type",
    "name": "Amber Type",
    "category": "Cinema",
    "previewText": "MAKE A DIFFERENCE",
    "behindPerson": false,
    "style": {
      "curated": true,
      "fontFamily": "Barlow Condensed",
      "fontWeight": 700,
      "fontSize": 31,
      "textTransform": "uppercase",
      "textColor": "#F0C88B",
      "highlightColor": "#FFFFFF",
      "highlightMode": "none",
      "strokeColor": "#111318",
      "strokeWidth": 0,
      "bgColor": "#111318",
      "bgOpacity": 0,
      "bgPadding": 6,
      "borderRadius": 6,
      "textShadow": true,
      "shadowColor": "#000000",
      "shadowBlur": 3,
      "shadowOffsetX": 0,
      "shadowOffsetY": 2,
      "glowIntensity": 0,
      "filter": "none",
      "backdropFilter": "none",
      "wordAnimation": "none",
      "presetDuration": 0.2,
      "wordsInRow": "3 Words",
      "letterSpacing": 1,
      "lineSpacing": 1.15
    }
  }
];

const DEFAULT_PRESET = CAPTION_PRESETS[0];

function getPresetsByCategory(category) {
  return !category || category === "All" ? CAPTION_PRESETS : CAPTION_PRESETS.filter(p => p.category === category);
}
function getPresetById(id) {
  return CAPTION_PRESETS.find(p => p.id === id) || null;
}

export { CATEGORIES, CAPTION_PRESETS, DEFAULT_PRESET, getPresetsByCategory, getPresetById };
