// Kept in sync with the static caption editor catalog (8 curated modern creator presets).
export const CATEGORIES = ["Viral", "Creator", "Clean", "Bold", "Editorial"];

export const CAPTION_PRESETS = [
  {
    id: "preset-moonshot-viral",
    name: "Moonshot Viral",
    category: "Viral",
    previewText: "VIRAL HIGHLIGHT",
    badge: "HOT",
    behindPerson: false,
    quickPick: true,
    style: {
      curated: true,
      fontFamily: "Montserrat",
      fontWeight: 900,
      fontSize: 34,
      textTransform: "uppercase",
      textColor: "#FFFFFF",
      highlightColor: "#000000",
      highlightBg: "#FFE600",
      highlightMode: "pill",
      strokeColor: "#000000",
      strokeWidth: 2,
      bgColor: "transparent",
      bgOpacity: 0,
      bgPadding: 8,
      borderRadius: 14,
      textShadow: true,
      shadowColor: "#000000",
      shadowBlur: 8,
      shadowOffsetX: 0,
      shadowOffsetY: 4,
      glowIntensity: 1,
      filter: "none",
      backdropFilter: "none",
      wordAnimation: "pop",
      presetDuration: 0.18,
      wordsInRow: "3 Words",
      letterSpacing: 1,
      lineSpacing: 1.2
    }
  },
  {
    id: "preset-hormozi-impact",
    name: "Hormozi Impact",
    category: "Viral",
    previewText: "MASSIVE RESULTS",
    badge: "VIRAL",
    behindPerson: false,
    quickPick: true,
    style: {
      curated: true,
      fontFamily: "Anton",
      fontWeight: 400,
      fontSize: 36,
      textTransform: "uppercase",
      textColor: "#FFFFFF",
      highlightColor: "#00FF66",
      highlightBg: "transparent",
      highlightMode: "word",
      strokeColor: "#000000",
      strokeWidth: 6,
      bgColor: "transparent",
      bgOpacity: 0,
      bgPadding: 6,
      borderRadius: 4,
      textShadow: true,
      shadowColor: "#000000",
      shadowBlur: 10,
      shadowOffsetX: 0,
      shadowOffsetY: 4,
      glowIntensity: 2,
      filter: "none",
      backdropFilter: "none",
      wordAnimation: "pop",
      presetDuration: 0.15,
      wordsInRow: "2 Words",
      letterSpacing: 1,
      lineSpacing: 1.15
    }
  },
  {
    id: "preset-studio-clean",
    name: "Studio Clean",
    category: "Clean",
    previewText: "Clean and focused",
    behindPerson: false,
    quickPick: true,
    style: {
      curated: true,
      fontFamily: "Inter",
      fontWeight: 700,
      fontSize: 28,
      textTransform: "none",
      textColor: "#FFFFFF",
      highlightColor: "#38BDF8",
      highlightBg: "rgba(0, 0, 0, 0.6)",
      highlightMode: "word",
      strokeColor: "#000000",
      strokeWidth: 0,
      bgColor: "#000000",
      bgOpacity: 60,
      bgPadding: 10,
      borderRadius: 12,
      textShadow: true,
      shadowColor: "#000000",
      shadowBlur: 4,
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      glowIntensity: 0,
      filter: "none",
      backdropFilter: "blur(8px)",
      wordAnimation: "classic",
      presetDuration: 0.2,
      wordsInRow: "3 Words",
      letterSpacing: 0,
      lineSpacing: 1.25
    }
  },
  {
    id: "preset-headline-punch",
    name: "Headline Punch",
    category: "Bold",
    previewText: "BREAKING NEWS",
    behindPerson: false,
    quickPick: true,
    style: {
      curated: true,
      fontFamily: "Bebas Neue",
      fontWeight: 400,
      fontSize: 38,
      textTransform: "uppercase",
      textColor: "#FFFFFF",
      highlightColor: "#EF4444",
      highlightBg: "transparent",
      highlightMode: "word",
      strokeColor: "#000000",
      strokeWidth: 3,
      bgColor: "transparent",
      bgOpacity: 0,
      bgPadding: 6,
      borderRadius: 6,
      textShadow: true,
      shadowColor: "#000000",
      shadowBlur: 6,
      shadowOffsetX: 0,
      shadowOffsetY: 3,
      glowIntensity: 1,
      filter: "none",
      backdropFilter: "none",
      wordAnimation: "pop",
      presetDuration: 0.18,
      wordsInRow: "2 Words",
      letterSpacing: 1.5,
      lineSpacing: 1.15
    }
  },
  {
    id: "preset-cyber-glow",
    name: "Cyber Glow",
    category: "Creator",
    previewText: "FUTURE VISION",
    behindPerson: false,
    quickPick: true,
    style: {
      curated: true,
      fontFamily: "Barlow",
      fontWeight: 800,
      fontSize: 32,
      textTransform: "uppercase",
      textColor: "#F43F5E",
      highlightColor: "#06B6D4",
      highlightBg: "transparent",
      highlightMode: "word",
      strokeColor: "#000000",
      strokeWidth: 2,
      bgColor: "transparent",
      bgOpacity: 0,
      bgPadding: 6,
      borderRadius: 8,
      textShadow: true,
      shadowColor: "#06B6D4",
      shadowBlur: 14,
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      glowIntensity: 4,
      filter: "none",
      backdropFilter: "none",
      wordAnimation: "neon",
      presetDuration: 0.22,
      wordsInRow: "3 Words",
      letterSpacing: 1,
      lineSpacing: 1.2
    }
  },
  {
    id: "preset-editorial-serif",
    name: "Editorial Serif",
    category: "Editorial",
    previewText: "Art of narrative",
    behindPerson: false,
    quickPick: true,
    style: {
      curated: true,
      fontFamily: "Libre Caslon Text",
      fontWeight: 400,
      fontStyle: "italic",
      fontSize: 27,
      textTransform: "none",
      textColor: "#FDFBF7",
      highlightColor: "#FDFBF7",
      highlightBg: "transparent",
      highlightMode: "word",
      strokeColor: "#000000",
      strokeWidth: 0,
      bgColor: "transparent",
      bgOpacity: 0,
      bgPadding: 6,
      borderRadius: 4,
      textShadow: true,
      shadowColor: "#000000",
      shadowBlur: 4,
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      glowIntensity: 0,
      filter: "none",
      backdropFilter: "none",
      wordAnimation: "elevate",
      presetDuration: 0.25,
      wordsInRow: "3 Words",
      letterSpacing: 0.5,
      lineSpacing: 1.3
    }
  },
  {
    id: "preset-dark-label",
    name: "Dark Label",
    category: "Creator",
    previewText: "LIME FOCUS",
    behindPerson: false,
    quickPick: true,
    style: {
      curated: true,
      fontFamily: "Barlow Condensed",
      fontWeight: 700,
      fontSize: 30,
      textTransform: "uppercase",
      textColor: "#FFFFFF",
      highlightColor: "#A3E635",
      highlightBg: "#18181B",
      highlightMode: "word",
      strokeColor: "#000000",
      strokeWidth: 0,
      bgColor: "#18181B",
      bgOpacity: 95,
      bgPadding: 10,
      borderRadius: 14,
      textShadow: false,
      shadowColor: "#000000",
      shadowBlur: 0,
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      glowIntensity: 0,
      filter: "none",
      backdropFilter: "none",
      wordAnimation: "pop",
      presetDuration: 0.2,
      wordsInRow: "3 Words",
      letterSpacing: 0.5,
      lineSpacing: 1.2
    }
  },
  {
    id: "preset-retro-pop",
    name: "Retro Pop",
    category: "Bold",
    previewText: "VINTAGE GROOVE",
    behindPerson: false,
    quickPick: true,
    style: {
      curated: true,
      fontFamily: "Archivo Black",
      fontWeight: 400,
      fontSize: 32,
      textTransform: "uppercase",
      textColor: "#FACC15",
      highlightColor: "#000000",
      highlightBg: "#FFFFFF",
      highlightMode: "pill",
      strokeColor: "#000000",
      strokeWidth: 2,
      bgColor: "transparent",
      bgOpacity: 0,
      bgPadding: 8,
      borderRadius: 12,
      textShadow: true,
      shadowColor: "#000000",
      shadowBlur: 6,
      shadowOffsetX: 0,
      shadowOffsetY: 3,
      glowIntensity: 1,
      filter: "none",
      backdropFilter: "none",
      wordAnimation: "pop",
      presetDuration: 0.2,
      wordsInRow: "2 Words",
      letterSpacing: 1,
      lineSpacing: 1.15
    }
  }
];

export const DEFAULT_PRESET = CAPTION_PRESETS[0];

export function getPresetsByCategory(category) {
  return !category || category === "All" ? CAPTION_PRESETS : CAPTION_PRESETS.filter(p => p.category === category);
}

export function getPresetById(id) {
  return CAPTION_PRESETS.find(p => p.id === id) || null;
}
