// Kept in sync with the static editor's five layered presets.
export const CAPTION_PRESETS = [
  {
    "id": "editorial-gold",
    "name": "Editorial Gold",
    "category": "Editorial",
    "previewText": "Make it count",
    "quickPick": true,
    "style": {
      "curated": true,
      "layered": true,
      "fontFamily": "Satoshi",
      "heroFontFamily": "Telma",
      "fontWeight": 700,
      "fontSize": 30,
      "textTransform": "none",
      "textColor": "#FFFFFF",
      "highlightColor": "#F9DB77",
      "highlightMode": "word",
      "strokeColor": "#000000",
      "strokeWidth": 0,
      "bgColor": "transparent",
      "bgOpacity": 0,
      "textShadow": true,
      "shadowColor": "#000000",
      "shadowBlur": 7,
      "shadowOffsetX": 0,
      "shadowOffsetY": 3,
      "wordAnimation": "float-up",
      "presetDuration": 0.26,
      "wordsInRow": "3 Words",
      "letterSpacing": -0.7,
      "lineSpacing": 1.08,
      "positionX": 50,
      "positionY": 45,
      "boxWidth": 88,
      "textAlign": "center"
    }
  },
  {
    "id": "bold-cut",
    "name": "Bold Cut",
    "category": "Bold",
    "previewText": "TRENDY EFFECT",
    "quickPick": true,
    "style": {
      "curated": true,
      "layered": true,
      "fontFamily": "Expose",
      "heroFontFamily": "Expose",
      "fontWeight": 900,
      "fontSize": 34,
      "textTransform": "uppercase",
      "textColor": "#FFFFFF",
      "highlightColor": "#D9DBE7",
      "highlightMode": "word",
      "strokeColor": "#000000",
      "strokeWidth": 0,
      "bgColor": "transparent",
      "bgOpacity": 0,
      "textShadow": true,
      "shadowColor": "#000000",
      "shadowBlur": 7,
      "shadowOffsetX": 0,
      "shadowOffsetY": 3,
      "wordAnimation": "slide-up",
      "presetDuration": 0.26,
      "wordsInRow": "3 Words",
      "letterSpacing": -0.7,
      "lineSpacing": 1.08,
      "positionX": 50,
      "positionY": 38,
      "boxWidth": 88,
      "textAlign": "center"
    }
  },
  {
    "id": "cyan-focus",
    "name": "Cyan Focus",
    "category": "Creator",
    "previewText": "3 Seconds to make",
    "quickPick": true,
    "style": {
      "curated": true,
      "layered": true,
      "fontFamily": "Chillax",
      "heroFontFamily": "Chillax",
      "fontWeight": 700,
      "fontSize": 30,
      "textTransform": "none",
      "textColor": "#FFFFFF",
      "highlightColor": "#64E6F2",
      "highlightMode": "word",
      "strokeColor": "#000000",
      "strokeWidth": 0,
      "bgColor": "transparent",
      "bgOpacity": 0,
      "textShadow": true,
      "shadowColor": "#000000",
      "shadowBlur": 7,
      "shadowOffsetX": 0,
      "shadowOffsetY": 3,
      "wordAnimation": "typewriter",
      "presetDuration": 0.36,
      "wordsInRow": "3 Words",
      "letterSpacing": -0.7,
      "lineSpacing": 1.08,
      "positionX": 50,
      "positionY": 46,
      "boxWidth": 88,
      "textAlign": "left"
    }
  },
  {
    "id": "ruby-script",
    "name": "Ruby Script",
    "category": "Editorial",
    "previewText": "CapCut Cheat code",
    "quickPick": true,
    "style": {
      "curated": true,
      "layered": true,
      "fontFamily": "Satoshi",
      "heroFontFamily": "Britney",
      "fontWeight": 700,
      "fontSize": 30,
      "textTransform": "none",
      "textColor": "#FFFFFF",
      "highlightColor": "#F22C42",
      "highlightMode": "word",
      "strokeColor": "#000000",
      "strokeWidth": 0,
      "bgColor": "transparent",
      "bgOpacity": 0,
      "textShadow": true,
      "shadowColor": "#000000",
      "shadowBlur": 7,
      "shadowOffsetX": 0,
      "shadowOffsetY": 3,
      "wordAnimation": "bouncy",
      "presetDuration": 0.26,
      "wordsInRow": "3 Words",
      "letterSpacing": -0.7,
      "lineSpacing": 1.08,
      "positionX": 50,
      "positionY": 45,
      "boxWidth": 88,
      "textAlign": "center"
    }
  },
  {
    "id": "kinetic-lime",
    "name": "Kinetic Lime",
    "category": "Viral",
    "previewText": "THE QUICK BROWN",
    "quickPick": true,
    "style": {
      "curated": true,
      "layered": true,
      "fontFamily": "Satoshi",
      "heroFontFamily": "Expose",
      "fontWeight": 700,
      "fontSize": 30,
      "textTransform": "uppercase",
      "textColor": "#FFFFFF",
      "highlightColor": "#D9FF00",
      "highlightMode": "word",
      "strokeColor": "#000000",
      "strokeWidth": 0,
      "bgColor": "transparent",
      "bgOpacity": 0,
      "textShadow": true,
      "shadowColor": "#000000",
      "shadowBlur": 7,
      "shadowOffsetX": 0,
      "shadowOffsetY": 3,
      "wordAnimation": "letters-up",
      "presetDuration": 0.36,
      "wordsInRow": "3 Words",
      "letterSpacing": -0.7,
      "lineSpacing": 1.08,
      "positionX": 50,
      "positionY": 42,
      "boxWidth": 88,
      "textAlign": "center"
    }
  }
];
export const CATEGORIES = [...new Set(CAPTION_PRESETS.map(p => p.category))];
export const DEFAULT_PRESET = CAPTION_PRESETS[0];
export const getPresetsByCategory = category => !category || category === "All" ? CAPTION_PRESETS : CAPTION_PRESETS.filter(p => p.category === category);
export const getPresetById = id => CAPTION_PRESETS.find(p => p.id === id) || null;
